"""
NLP Engine – Extracts medical symptom keywords from free-text input.

Pipeline:
  1. Clean text (lowercase, strip punctuation / numbers)
  2. Tokenize & remove stop words
  3. Lemmatize
  4. Match tokens / bigrams / trigrams against a medical lexicon
  5. Return matched canonical symptom keys + unrecognized tokens
"""

import re

# ─── Medical Lexicon ──────────────────────────────────────
# Maps user-facing phrases → canonical symptom key used by the ML model.
# This lexicon is intentionally comprehensive to handle common
# ways patients describe their symptoms.

MEDICAL_LEXICON = {
    "stomach pain": "abdominal_pain",
    "belly pain": "abdominal_pain",
    "tummy pain": "abdominal_pain",
    "abdominal pain": "abdominal_pain",
    "stomach ache": "abdominal_pain",
    "belly ache": "abdominal_pain",
    "tummy ache": "abdominal_pain",
    "stomach cramp": "abdominal_pain",
    "abdominal cramp": "abdominal_pain",
    "pain in stomach": "abdominal_pain",
    "pain in abdomen": "abdominal_pain",
    "nausea": "nausea",
    "feeling nauseous": "nausea",
    "feel sick": "nausea",
    "queasy": "nausea",
    "vomiting": "vomiting",
    "throwing up": "vomiting",
    "vomit": "vomiting",
    "puking": "vomiting",
    "bloating": "swelling_of_stomach",
    "bloated": "swelling_of_stomach",
    "feel bloated": "swelling_of_stomach",
    "gas": "swelling_of_stomach",
    "flatulence": "swelling_of_stomach",
    "diarrhea": "diarrhoea",
    "loose stool": "diarrhoea",
    "loose motion": "diarrhoea",
    "watery stool": "diarrhoea",
    "runny stool": "diarrhoea",
    "frequent stool": "diarrhoea",
    "constipation": "constipation",
    "hard stool": "constipation",
    "difficulty passing stool": "constipation",
    "infrequent bowel movement": "constipation",
    "heartburn": "acidity",
    "acid reflux": "acidity",
    "burning chest": "acidity",
    "burning in chest": "acidity",
    "chest burning": "acidity",
    "regurgitation": "acidity",
    "loss of appetite": "loss_of_appetite",
    "no appetite": "loss_of_appetite",
    "not hungry": "loss_of_appetite",
    "poor appetite": "loss_of_appetite",
    "weight loss": "weight_loss",
    "losing weight": "weight_loss",
    "unintentional weight loss": "weight_loss",
    "blood in stool": "bloody_stool",
    "bloody stool": "bloody_stool",
    "rectal bleeding": "bloody_stool",
    "black stool": "bloody_stool",
    "tarry stool": "bloody_stool",
    "dark stool": "bloody_stool",
    "vomiting blood": "stomach_bleeding",
    "blood vomit": "stomach_bleeding",
    "rigid abdomen": "swelling_of_stomach",
    "abdominal rigidity": "swelling_of_stomach",
    "hard abdomen": "swelling_of_stomach",
    "dehydration": "dehydration",
    "severe dehydration": "dehydration",
    "dry mouth": "dehydration",
    "indigestion": "indigestion",
    "upset stomach": "indigestion",
    "difficulty swallowing": "patches_in_throat",
    "trouble swallowing": "patches_in_throat",
    "chest pain": "chest_pain",
    "chest tightness": "chest_pain",
    "tight chest": "chest_pain",
    "pressure in chest": "chest_pain",
    "sweating": "sweating",
    "cold sweat": "sweating",
    "excessive sweating": "sweating",
    "shortness of breath": "breathlessness",
    "breathlessness": "breathlessness",
    "difficulty breathing": "breathlessness",
    "hard to breathe": "breathlessness",
    "can't breathe": "breathlessness",
    "palpitation": "palpitations",
    "palpitations": "palpitations",
    "heart racing": "palpitations",
    "rapid heartbeat": "palpitations",
    "irregular heartbeat": "palpitations",
    "dizziness": "dizziness",
    "dizzy": "dizziness",
    "lightheaded": "dizziness",
    "light headed": "dizziness",
    "fainting": "loss_of_balance",
    "faint": "loss_of_balance",
    "passed out": "loss_of_balance",
    "loss of consciousness": "loss_of_balance",
    "unconsciousness": "loss_of_balance",
    "jaw pain": "neck_pain",
    "pain in jaw": "neck_pain",
    "pain radiating to jaw": "neck_pain",
    "cough": "cough",
    "dry cough": "cough",
    "persistent cough": "cough",
    "productive cough": "mucoid_sputum",
    "coughing mucus": "mucoid_sputum",
    "cough with phlegm": "mucoid_sputum",
    "fever": "high_fever",
    "high fever": "high_fever",
    "temperature": "high_fever",
    "chills": "chills",
    "body ache": "muscle_pain",
    "body pain": "muscle_pain",
    "muscle pain": "muscle_pain",
    "muscle ache": "muscle_pain",
    "sore throat": "throat_irritation",
    "throat pain": "throat_irritation",
    "runny nose": "runny_nose",
    "nasal congestion": "runny_nose",
    "stuffy nose": "runny_nose",
    "sneezing": "continuous_sneezing",
    "fatigue": "fatigue",
    "tired": "fatigue",
    "tiredness": "fatigue",
    "exhaustion": "fatigue",
    "weakness": "fatigue",
    "rapid breathing": "fast_heart_rate",
    "fast breathing": "fast_heart_rate",
    "bluish lips": "cold_hands_and_feets",
    "blue lips": "cold_hands_and_feets",
    "bluish fingertips": "cold_hands_and_feets",
    "blue fingertips": "cold_hands_and_feets",
    "frequent urination": "continuous_feel_of_urine",
    "urinating frequently": "continuous_feel_of_urine",
    "excessive thirst": "polyuria",
    "always thirsty": "polyuria",
    "increased thirst": "polyuria",
    "blurred vision": "blurred_and_distorted_vision",
    "blurry vision": "blurred_and_distorted_vision",
    "vision blurred": "blurred_and_distorted_vision",
    "slow healing": "pus_filled_pimples",
    "wounds not healing": "pus_filled_pimples",
    "numbness": "weakness_in_limbs",
    "tingling": "weakness_in_limbs",
    "pins and needles": "weakness_in_limbs",
    "increased hunger": "excessive_hunger",
    "always hungry": "excessive_hunger",
    "fruity breath": "acidity",
    "fruity smelling breath": "acidity",
    "confusion": "altered_sensorium",
    "confused": "altered_sensorium",
    "disoriented": "altered_sensorium",
    "headache": "headache",
    "head pain": "headache",
    "severe headache": "headache",
    "worst headache": "headache",
    "throbbing headache": "headache",
    "migraine": "headache",
    "sensitivity to light": "visual_disturbances",
    "light sensitivity": "visual_disturbances",
    "photophobia": "visual_disturbances",
    "sensitivity to sound": "visual_disturbances",
    "sound sensitivity": "visual_disturbances",
    "aura": "visual_disturbances",
    "visual aura": "visual_disturbances",
    "anxiety": "anxiety",
    "feeling anxious": "anxiety",
    "nervousness": "anxiety",
    "nervous": "anxiety",
    "worry": "anxiety",
    "excessive worry": "anxiety",
    "restlessness": "restlessness",
    "restless": "restlessness",
    "can't relax": "restlessness",
    "irritability": "irritability",
    "irritable": "irritability",
    "sleep problem": "restlessness",
    "insomnia": "restlessness",
    "trouble sleeping": "restlessness",
    "can't sleep": "restlessness",
    "difficulty concentrating": "lack_of_concentration",
    "can't concentrate": "lack_of_concentration",
    "poor concentration": "lack_of_concentration",
    "muscle tension": "muscle_weakness",
    "tense muscles": "muscle_weakness",
    "panic": "anxiety",
    "panic attack": "anxiety",
    "vision loss": "visual_disturbances",
    "abnormal menstruation": "abnormal_menstruation",
    "acidity": "acidity",
    "acute liver failure": "acute_liver_failure",
    "altered sensorium": "altered_sensorium",
    "back pain": "back_pain",
    "blackheads": "blackheads",
    "bladder discomfort": "bladder_discomfort",
    "blister": "blister",
    "blood in sputum": "blood_in_sputum",
    "blurred and distorted vision": "blurred_and_distorted_vision",
    "brittle nails": "brittle_nails",
    "bruising": "bruising",
    "burning micturition": "burning_micturition",
    "cold hands and feets": "cold_hands_and_feets",
    "coma": "coma",
    "congestion": "congestion",
    "continuous feel of urine": "continuous_feel_of_urine",
    "continuous sneezing": "continuous_sneezing",
    "cramps": "cramps",
    "dark urine": "dark_urine",
    "depression": "depression",
    "diarrhoea": "diarrhoea",
    "dischromic  patches": "dischromic__patches",
    "distention of abdomen": "distention_of_abdomen",
    "drying and tingling lips": "drying_and_tingling_lips",
    "enlarged thyroid": "enlarged_thyroid",
    "excessive hunger": "excessive_hunger",
    "extra marital contacts": "extra_marital_contacts",
    "family history": "family_history",
    "fast heart rate": "fast_heart_rate",
    "fluid overload": "fluid_overload",
    "foul smell of urine": "foul_smell_of_urine",
    "hip joint pain": "hip_joint_pain",
    "history of alcohol consumption": "history_of_alcohol_consumption",
    "increased appetite": "increased_appetite",
    "inflammatory nails": "inflammatory_nails",
    "internal itching": "internal_itching",
    "irregular sugar level": "irregular_sugar_level",
    "irritation in anus": "irritation_in_anus",
    "itching": "itching",
    "joint pain": "joint_pain",
    "knee pain": "knee_pain",
    "lack of concentration": "lack_of_concentration",
    "lethargy": "lethargy",
    "loss of balance": "loss_of_balance",
    "loss of smell": "loss_of_smell",
    "malaise": "malaise",
    "mild fever": "mild_fever",
    "mood swings": "mood_swings",
    "movement stiffness": "movement_stiffness",
    "mucoid sputum": "mucoid_sputum",
    "muscle wasting": "muscle_wasting",
    "muscle weakness": "muscle_weakness",
    "neck pain": "neck_pain",
    "nodal skin eruptions": "nodal_skin_eruptions",
    "obesity": "obesity",
    "pain behind the eyes": "pain_behind_the_eyes",
    "pain during bowel movements": "pain_during_bowel_movements",
    "pain in anal region": "pain_in_anal_region",
    "painful walking": "painful_walking",
    "passage of gases": "passage_of_gases",
    "patches in throat": "patches_in_throat",
    "phlegm": "phlegm",
    "polyuria": "polyuria",
    "prominent veins on calf": "prominent_veins_on_calf",
    "puffy face and eyes": "puffy_face_and_eyes",
    "pus filled pimples": "pus_filled_pimples",
    "receiving blood transfusion": "receiving_blood_transfusion",
    "receiving unsterile injections": "receiving_unsterile_injections",
    "red sore around nose": "red_sore_around_nose",
    "red spots over body": "red_spots_over_body",
    "redness of eyes": "redness_of_eyes",
    "rusty sputum": "rusty_sputum",
    "scurring": "scurring",
    "shivering": "shivering",
    "silver like dusting": "silver_like_dusting",
    "sinus pressure": "sinus_pressure",
    "skin peeling": "skin_peeling",
    "skin rash": "skin_rash",
    "slurred speech": "slurred_speech",
    "small dents in nails": "small_dents_in_nails",
    "spinning movements": "spinning_movements",
    "spotting  urination": "spotting__urination",
    "stiff neck": "stiff_neck",
    "stomach bleeding": "stomach_bleeding",
    "sunken eyes": "sunken_eyes",
    "swelled lymph nodes": "swelled_lymph_nodes",
    "swelling joints": "swelling_joints",
    "swelling of stomach": "swelling_of_stomach",
    "swollen blood vessels": "swollen_blood_vessels",
    "swollen extremeties": "swollen_extremeties",
    "swollen legs": "swollen_legs",
    "throat irritation": "throat_irritation",
    "toxic look (typhos)": "toxic_look_(typhos)",
    "ulcers on tongue": "ulcers_on_tongue",
    "unsteadiness": "unsteadiness",
    "visual disturbances": "visual_disturbances",
    "watering from eyes": "watering_from_eyes",
    "weakness in limbs": "weakness_in_limbs",
    "weakness of one body side": "weakness_of_one_body_side",
    "weight gain": "weight_gain",
    "yellow crust ooze": "yellow_crust_ooze",
    "yellow urine": "yellow_urine",
    "yellowing of eyes": "yellowing_of_eyes",
    "yellowish skin": "yellowish_skin",
    "yellow skin": "yellowish_skin",

    # ─── EXPANDED GENERIC / CASUAL PHRASES ────────────────────
    # Eye-related
    "eye pain": "pain_behind_the_eyes",
    "pain in eye": "pain_behind_the_eyes",
    "pain in eyes": "pain_behind_the_eyes",
    "pain in my eye": "pain_behind_the_eyes",
    "pain in my eyes": "pain_behind_the_eyes",
    "eyes hurt": "pain_behind_the_eyes",
    "eye hurts": "pain_behind_the_eyes",
    "my eyes hurt": "pain_behind_the_eyes",
    "my eye hurts": "pain_behind_the_eyes",
    "sore eyes": "pain_behind_the_eyes",
    "eyes are red": "redness_of_eyes",
    "red eyes": "redness_of_eyes",
    "eye redness": "redness_of_eyes",
    "bloodshot eyes": "redness_of_eyes",
    "watery eyes": "watering_from_eyes",
    "eyes watering": "watering_from_eyes",
    "teary eyes": "watering_from_eyes",
    "tears": "watering_from_eyes",
    "yellow eyes": "yellowing_of_eyes",
    "eyes are yellow": "yellowing_of_eyes",
    "can't see": "blurred_and_distorted_vision",
    "can't see clearly": "blurred_and_distorted_vision",
    "poor vision": "blurred_and_distorted_vision",
    "vision problem": "blurred_and_distorted_vision",
    "vision problems": "blurred_and_distorted_vision",
    "fuzzy vision": "blurred_and_distorted_vision",
    "hazy vision": "blurred_and_distorted_vision",
    "seeing blurry": "blurred_and_distorted_vision",
    "puffy eyes": "puffy_face_and_eyes",
    "swollen eyes": "puffy_face_and_eyes",

    # Head / Neck
    "head hurts": "headache",
    "my head hurts": "headache",
    "head pain": "headache",
    "head is pounding": "headache",
    "pounding head": "headache",
    "splitting headache": "headache",
    "tension headache": "headache",
    "neck hurts": "neck_pain",
    "my neck hurts": "neck_pain",
    "sore neck": "neck_pain",
    "neck is stiff": "stiff_neck",
    "stiffness in neck": "stiff_neck",
    "can't move neck": "stiff_neck",

    # Throat / Mouth
    "throat hurts": "throat_irritation",
    "my throat hurts": "throat_irritation",
    "scratchy throat": "throat_irritation",
    "irritated throat": "throat_irritation",
    "itchy throat": "throat_irritation",
    "dry throat": "throat_irritation",
    "swollen throat": "patches_in_throat",
    "lump in throat": "patches_in_throat",
    "hard to swallow": "patches_in_throat",
    "can't swallow": "patches_in_throat",
    "tongue sore": "ulcers_on_tongue",
    "tongue ulcer": "ulcers_on_tongue",
    "sore on tongue": "ulcers_on_tongue",
    "mouth sore": "ulcers_on_tongue",
    "mouth ulcer": "ulcers_on_tongue",

    # Chest / Heart
    "chest hurts": "chest_pain",
    "my chest hurts": "chest_pain",
    "pain in chest": "chest_pain",
    "pain in my chest": "chest_pain",
    "chest discomfort": "chest_pain",
    "heart pain": "chest_pain",
    "my heart hurts": "chest_pain",
    "heart is racing": "palpitations",
    "heart beating fast": "palpitations",
    "heart pounding": "palpitations",
    "can't catch breath": "breathlessness",
    "out of breath": "breathlessness",
    "gasping": "breathlessness",
    "breathing problem": "breathlessness",
    "breathing difficulty": "breathlessness",
    "breathing problems": "breathlessness",
    "trouble breathing": "breathlessness",
    "wheezing": "breathlessness",

    # Stomach / Digestive (more variants)
    "stomach hurts": "abdominal_pain",
    "my stomach hurts": "abdominal_pain",
    "belly hurts": "abdominal_pain",
    "my belly hurts": "abdominal_pain",
    "tummy hurts": "abdominal_pain",
    "my tummy hurts": "abdominal_pain",
    "gut pain": "abdominal_pain",
    "lower abdomen pain": "abdominal_pain",
    "upper abdomen pain": "abdominal_pain",
    "abdomen hurts": "abdominal_pain",
    "can't eat": "loss_of_appetite",
    "don't feel like eating": "loss_of_appetite",
    "food not digesting": "indigestion",
    "food sits heavy": "indigestion",
    "heavy stomach": "indigestion",
    "stomach feels heavy": "indigestion",
    "passing gas": "passage_of_gases",
    "farting": "passage_of_gases",
    "gassy": "passage_of_gases",
    "lots of gas": "passage_of_gases",
    "feel like vomiting": "nausea",
    "about to throw up": "nausea",
    "want to vomit": "nausea",
    "stomach is upset": "indigestion",
    "swollen belly": "distention_of_abdomen",
    "belly is swollen": "distention_of_abdomen",
    "abdomen is swollen": "distention_of_abdomen",
    "stomach is swollen": "distention_of_abdomen",
    "big belly": "distention_of_abdomen",

    # Back
    "back hurts": "back_pain",
    "my back hurts": "back_pain",
    "lower back pain": "back_pain",
    "upper back pain": "back_pain",
    "backache": "back_pain",
    "sore back": "back_pain",
    "back is killing me": "back_pain",

    # Limbs / Joints / Muscles
    "leg pain": "muscle_pain",
    "leg hurts": "muscle_pain",
    "my leg hurts": "muscle_pain",
    "legs hurt": "muscle_pain",
    "my legs hurt": "muscle_pain",
    "sore legs": "muscle_pain",
    "arm pain": "muscle_pain",
    "arm hurts": "muscle_pain",
    "my arm hurts": "muscle_pain",
    "arms hurt": "muscle_pain",
    "sore arms": "muscle_pain",
    "finger pain": "joint_pain",
    "finger hurts": "joint_pain",
    "my finger hurts": "joint_pain",
    "fingers hurt": "joint_pain",
    "hand pain": "joint_pain",
    "hand hurts": "joint_pain",
    "my hand hurts": "joint_pain",
    "hands hurt": "joint_pain",
    "wrist pain": "joint_pain",
    "wrist hurts": "joint_pain",
    "foot pain": "painful_walking",
    "foot hurts": "painful_walking",
    "my foot hurts": "painful_walking",
    "feet hurt": "painful_walking",
    "my feet hurt": "painful_walking",
    "sore feet": "painful_walking",
    "ankle pain": "joint_pain",
    "ankle hurts": "joint_pain",
    "shoulder pain": "joint_pain",
    "shoulder hurts": "joint_pain",
    "my shoulder hurts": "joint_pain",
    "elbow pain": "joint_pain",
    "elbow hurts": "joint_pain",
    "joints hurt": "joint_pain",
    "my joints hurt": "joint_pain",
    "stiff joints": "joint_pain",
    "achy joints": "joint_pain",
    "joints ache": "joint_pain",
    "knee hurts": "knee_pain",
    "my knee hurts": "knee_pain",
    "knees hurt": "knee_pain",
    "sore knee": "knee_pain",
    "hip pain": "hip_joint_pain",
    "hip hurts": "hip_joint_pain",
    "my hip hurts": "hip_joint_pain",
    "sore muscles": "muscle_pain",
    "muscles hurt": "muscle_pain",
    "muscles are sore": "muscle_pain",
    "muscle soreness": "muscle_pain",
    "weak muscles": "muscle_weakness",
    "muscles feel weak": "muscle_weakness",
    "no strength": "muscle_weakness",
    "feeling weak": "muscle_weakness",
    "can't walk": "painful_walking",
    "trouble walking": "painful_walking",
    "difficulty walking": "painful_walking",
    "hurts to walk": "painful_walking",
    "pain when walking": "painful_walking",
    "legs are swollen": "swollen_legs",
    "swollen leg": "swollen_legs",
    "swollen feet": "swollen_legs",
    "swollen ankles": "swollen_legs",
    "numb hands": "weakness_in_limbs",
    "numb feet": "weakness_in_limbs",
    "numb fingers": "weakness_in_limbs",
    "numb toes": "weakness_in_limbs",
    "numb legs": "weakness_in_limbs",
    "numb arms": "weakness_in_limbs",
    "hands are numb": "weakness_in_limbs",
    "feet are numb": "weakness_in_limbs",
    "cold hands": "cold_hands_and_feets",
    "cold feet": "cold_hands_and_feets",
    "cold fingers": "cold_hands_and_feets",
    "hands are cold": "cold_hands_and_feets",
    "feet are cold": "cold_hands_and_feets",

    # Skin
    "rash": "skin_rash",
    "rashes": "skin_rash",
    "skin irritation": "skin_rash",
    "red skin": "skin_rash",
    "spots on skin": "red_spots_over_body",
    "red spots": "red_spots_over_body",
    "skin spots": "red_spots_over_body",
    "bumps on skin": "nodal_skin_eruptions",
    "skin bumps": "nodal_skin_eruptions",
    "lumps on skin": "nodal_skin_eruptions",
    "itchy": "itching",
    "itchy skin": "itching",
    "skin itching": "itching",
    "scratching a lot": "itching",
    "body itching": "itching",
    "itch all over": "itching",
    "skin is peeling": "skin_peeling",
    "peeling skin": "skin_peeling",
    "flaky skin": "skin_peeling",
    "dry skin": "skin_peeling",
    "blister on skin": "blister",
    "blisters": "blister",
    "skin blister": "blister",
    "bruise": "bruising",
    "bruises": "bruising",
    "easy bruising": "bruising",
    "bruise easily": "bruising",
    "pimples": "pus_filled_pimples",
    "acne": "pus_filled_pimples",
    "breakout": "pus_filled_pimples",
    "skin breakout": "pus_filled_pimples",
    "nose sore": "red_sore_around_nose",
    "sore on nose": "red_sore_around_nose",
    "sore around nose": "red_sore_around_nose",
    "dark patches": "dischromic__patches",
    "skin patches": "dischromic__patches",
    "discolored skin": "dischromic__patches",
    "skin discoloration": "dischromic__patches",
    "swollen glands": "swelled_lymph_nodes",
    "swollen lymph nodes": "swelled_lymph_nodes",
    "swollen nodes": "swelled_lymph_nodes",
    "puffy face": "puffy_face_and_eyes",
    "face is swollen": "puffy_face_and_eyes",
    "swollen face": "puffy_face_and_eyes",

    # Fever / Temperature (more variants)
    "feeling hot": "high_fever",
    "burning up": "high_fever",
    "temperature is high": "high_fever",
    "got a fever": "high_fever",
    "feverish": "high_fever",
    "feeling feverish": "high_fever",
    "slight fever": "mild_fever",
    "low grade fever": "mild_fever",
    "low fever": "mild_fever",
    "mild temperature": "mild_fever",
    "feeling cold": "chills",
    "feel cold": "chills",
    "shaking": "shivering",
    "body shaking": "shivering",
    "trembling": "shivering",

    # General / Systemic
    "feeling unwell": "malaise",
    "not feeling well": "malaise",
    "don't feel well": "malaise",
    "feel unwell": "malaise",
    "feel bad": "malaise",
    "feeling bad": "malaise",
    "feeling awful": "malaise",
    "under the weather": "malaise",
    "generally unwell": "malaise",
    "feel ill": "malaise",
    "feeling ill": "malaise",
    "no energy": "fatigue",
    "low energy": "fatigue",
    "lack of energy": "fatigue",
    "drained": "fatigue",
    "feeling drained": "fatigue",
    "worn out": "fatigue",
    "run down": "fatigue",
    "sluggish": "lethargy",
    "feeling sluggish": "lethargy",
    "lazy feeling": "lethargy",
    "lethargic": "lethargy",
    "feeling lethargic": "lethargy",
    "lost weight": "weight_loss",
    "dropping weight": "weight_loss",
    "getting thinner": "weight_loss",
    "gained weight": "weight_gain",
    "putting on weight": "weight_gain",
    "getting heavier": "weight_gain",
    "getting fat": "weight_gain",
    "overweight": "obesity",
    "very thirsty": "polyuria",
    "drinking a lot of water": "polyuria",
    "so thirsty": "polyuria",
    "mouth is dry": "dehydration",
    "lips are dry": "drying_and_tingling_lips",
    "dry lips": "drying_and_tingling_lips",
    "chapped lips": "drying_and_tingling_lips",
    "tingling lips": "drying_and_tingling_lips",
    "lips tingling": "drying_and_tingling_lips",
    "sweat a lot": "sweating",
    "sweating a lot": "sweating",
    "night sweats": "sweating",
    "profuse sweating": "sweating",
    "sunken eyes": "sunken_eyes",
    "eyes are sunken": "sunken_eyes",
    "dark circles": "sunken_eyes",
    "hollow eyes": "sunken_eyes",

    # Urinary
    "painful urination": "burning_micturition",
    "burning urination": "burning_micturition",
    "pain when urinating": "burning_micturition",
    "hurts to urinate": "burning_micturition",
    "hurts to pee": "burning_micturition",
    "burning when peeing": "burning_micturition",
    "peeing burns": "burning_micturition",
    "painful peeing": "burning_micturition",
    "urine burns": "burning_micturition",
    "peeing a lot": "continuous_feel_of_urine",
    "urinating a lot": "continuous_feel_of_urine",
    "need to pee": "continuous_feel_of_urine",
    "always need to pee": "continuous_feel_of_urine",
    "constant urge to urinate": "continuous_feel_of_urine",
    "dark colored urine": "dark_urine",
    "brown urine": "dark_urine",
    "dark pee": "dark_urine",
    "urine is dark": "dark_urine",
    "smelly urine": "foul_smell_of_urine",
    "urine smells bad": "foul_smell_of_urine",
    "stinky urine": "foul_smell_of_urine",
    "bad smelling urine": "foul_smell_of_urine",
    "urine is yellow": "yellow_urine",
    "bright yellow urine": "yellow_urine",
    "blood in urine": "spotting__urination",
    "bloody urine": "spotting__urination",
    "bladder pain": "bladder_discomfort",
    "bladder pressure": "bladder_discomfort",
    "bladder hurts": "bladder_discomfort",

    # Mental Health / Neurological
    "feeling sad": "depression",
    "sad": "depression",
    "feeling depressed": "depression",
    "depressed": "depression",
    "hopeless": "depression",
    "feeling hopeless": "depression",
    "no motivation": "depression",
    "stressed": "anxiety",
    "stress": "anxiety",
    "feeling stressed": "anxiety",
    "worried": "anxiety",
    "feeling worried": "anxiety",
    "tense": "anxiety",
    "feeling tense": "anxiety",
    "can't focus": "lack_of_concentration",
    "trouble focusing": "lack_of_concentration",
    "hard to focus": "lack_of_concentration",
    "losing focus": "lack_of_concentration",
    "can't think straight": "lack_of_concentration",
    "brain fog": "lack_of_concentration",
    "forgetful": "lack_of_concentration",
    "mood changes": "mood_swings",
    "emotional": "mood_swings",
    "moody": "mood_swings",
    "feeling moody": "mood_swings",
    "cranky": "irritability",
    "grumpy": "irritability",
    "easily annoyed": "irritability",
    "agitated": "irritability",
    "can't sit still": "restlessness",
    "fidgety": "restlessness",
    "sleep problems": "restlessness",
    "poor sleep": "restlessness",
    "not sleeping well": "restlessness",
    "slurring words": "slurred_speech",
    "speech problem": "slurred_speech",
    "can't speak properly": "slurred_speech",
    "talking funny": "slurred_speech",

    # Nose / Sinus
    "nose is running": "runny_nose",
    "running nose": "runny_nose",
    "nose is blocked": "runny_nose",
    "blocked nose": "runny_nose",
    "nose blocked": "runny_nose",
    "can't smell": "loss_of_smell",
    "lost smell": "loss_of_smell",
    "no smell": "loss_of_smell",
    "can't smell anything": "loss_of_smell",
    "sinus": "sinus_pressure",
    "sinus pain": "sinus_pressure",
    "sinusitis": "sinus_pressure",
    "face pressure": "sinus_pressure",
    "pressure in face": "sinus_pressure",

    # Cough variants
    "coughing": "cough",
    "keep coughing": "cough",
    "can't stop coughing": "cough",
    "coughing a lot": "cough",
    "wet cough": "mucoid_sputum",
    "coughing up mucus": "mucoid_sputum",
    "coughing up phlegm": "mucoid_sputum",
    "spitting mucus": "mucoid_sputum",
    "spitting phlegm": "mucoid_sputum",
    "coughing blood": "blood_in_sputum",
    "coughing up blood": "blood_in_sputum",
    "blood when coughing": "blood_in_sputum",

    # Balance / Consciousness
    "off balance": "loss_of_balance",
    "losing balance": "loss_of_balance",
    "unsteady": "unsteadiness",
    "feeling unsteady": "unsteadiness",
    "wobbly": "unsteadiness",
    "stumbling": "unsteadiness",
    "room is spinning": "spinning_movements",
    "everything is spinning": "spinning_movements",
    "vertigo": "spinning_movements",
    "world spinning": "spinning_movements",
    "feel like falling": "loss_of_balance",
    "almost fainted": "loss_of_balance",
    "about to faint": "loss_of_balance",
    "blacked out": "loss_of_balance",

    # Appetite / Hunger
    "hungry all the time": "excessive_hunger",
    "eating a lot": "excessive_hunger",
    "eating too much": "increased_appetite",
    "appetite increased": "increased_appetite",
    "big appetite": "increased_appetite",
    "eating more than usual": "increased_appetite",
    "not eating": "loss_of_appetite",
    "skipping meals": "loss_of_appetite",
    "food doesn't taste good": "loss_of_appetite",

    # Bowel / Rectal
    "pain when pooping": "pain_during_bowel_movements",
    "hurts to poop": "pain_during_bowel_movements",
    "painful bowel movement": "pain_during_bowel_movements",
    "anal pain": "pain_in_anal_region",
    "butt pain": "pain_in_anal_region",
    "rectal pain": "pain_in_anal_region",
    "anus hurts": "pain_in_anal_region",
    "itchy anus": "irritation_in_anus",
    "anal itching": "irritation_in_anus",
    "rectal itching": "irritation_in_anus",
    "blood when pooping": "bloody_stool",
    "blood after pooping": "bloody_stool",
    "blood in poop": "bloody_stool",

    # Nails
    "nails breaking": "brittle_nails",
    "weak nails": "brittle_nails",
    "nails are weak": "brittle_nails",
    "nails cracking": "brittle_nails",
    "dents in nails": "small_dents_in_nails",
    "nail dents": "small_dents_in_nails",
    "nails have dents": "small_dents_in_nails",
    "nail inflammation": "inflammatory_nails",
    "inflamed nails": "inflammatory_nails",
    "swollen nails": "inflammatory_nails",
    "nail infection": "inflammatory_nails",

    # Menstrual
    "irregular periods": "abnormal_menstruation",
    "irregular period": "abnormal_menstruation",
    "missed period": "abnormal_menstruation",
    "late period": "abnormal_menstruation",
    "heavy periods": "abnormal_menstruation",
    "heavy period": "abnormal_menstruation",
    "painful periods": "abnormal_menstruation",
    "period problems": "abnormal_menstruation",
    "menstrual problems": "abnormal_menstruation",
    "period cramps": "cramps",
    "menstrual cramps": "cramps",
    "cramping": "cramps",
    "muscle cramps": "cramps",
    "leg cramps": "cramps",

    # Sugar / Diabetes indicators
    "high sugar": "irregular_sugar_level",
    "low sugar": "irregular_sugar_level",
    "blood sugar high": "irregular_sugar_level",
    "blood sugar low": "irregular_sugar_level",
    "sugar level high": "irregular_sugar_level",
    "sugar level low": "irregular_sugar_level",
    "diabetic": "irregular_sugar_level",

    # Thyroid
    "thyroid problem": "enlarged_thyroid",
    "thyroid swelling": "enlarged_thyroid",
    "swollen thyroid": "enlarged_thyroid",
    "goiter": "enlarged_thyroid",
    "neck swelling": "enlarged_thyroid",

    # Veins
    "varicose veins": "prominent_veins_on_calf",
    "veins showing": "prominent_veins_on_calf",
    "bulging veins": "prominent_veins_on_calf",
    "veins on leg": "prominent_veins_on_calf",
    "swollen veins": "swollen_blood_vessels",

    # Alcohol / History
    "drink alcohol": "history_of_alcohol_consumption",
    "drinking alcohol": "history_of_alcohol_consumption",
    "heavy drinker": "history_of_alcohol_consumption",
    "alcoholic": "history_of_alcohol_consumption",
    "drink a lot": "history_of_alcohol_consumption",

    # Generic standalone pain as fallback
    "pain": "muscle_pain",
    "hurts": "muscle_pain",
    "ache": "muscle_pain",
    "aching": "muscle_pain",
    "sore": "muscle_pain",
    "soreness": "muscle_pain",
    "stiff": "movement_stiffness",
    "stiffness": "movement_stiffness",
    "swelling": "swelling_joints",
    "swollen": "swelling_joints",
}


import os
import json

# Auto-inject all 131 Kaggle dataset columns into the Lexicon!
try:
    script_dir = os.path.dirname(os.path.abspath(__file__))
    columns_path = os.path.join(script_dir, "..", "ml", "symptom_columns.json")
    with open(columns_path, "r") as f:
        ml_symptoms = json.load(f)
        for sym in ml_symptoms:
            # "yellowish_skin" -> "yellowish skin"
            phrase = sym.replace("_", " ").strip()
            if phrase not in MEDICAL_LEXICON:
                MEDICAL_LEXICON[phrase] = sym
            # Add specific common variants for new Kaggle terms
            if "yellowish" in sym:
                MEDICAL_LEXICON[sym.replace("yellowish", "yellow").replace("_", " ").strip()] = sym
except Exception as e:
    pass # Falback to hardcoded lexicon if file is not found

# Build a sorted list of phrases (longest first) so multi-word matches
# take priority over single-word matches.
_PHRASES_SORTED = sorted(MEDICAL_LEXICON.keys(), key=len, reverse=True)

# Collect all single-word lemma forms for fallback matching
_SINGLE_WORD_KEYS = {k for k in MEDICAL_LEXICON if " " not in k}


def _clean(text: str) -> str:
    """Lowercase, strip punctuation (keep spaces), collapse whitespace."""
    text = text.lower()
    text = re.sub(r"[^a-z\s']", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text


def extract_symptoms(raw_text: str) -> dict:
    """
    Extract canonical symptom keys from free-text input.

    Returns:
        {
            "matched": ["abdominal_pain", "nausea", ...],
            "unrecognized": ["xyz", ...]
        }
    """
    cleaned = _clean(raw_text)
    matched = set()
    remaining = cleaned

    # Pass 1 – greedy multi-word phrase matching (longest first)
    for phrase in _PHRASES_SORTED:
        if phrase in remaining:
            matched.add(MEDICAL_LEXICON[phrase])
            remaining = remaining.replace(phrase, " ")

    # Pass 2 – single-word fallback for leftover tokens
    remaining = re.sub(r"\s+", " ", remaining).strip()
    leftover_tokens = remaining.split() if remaining else []
    unrecognized = []

    stop_words = {
        "i", "me", "my", "have", "has", "had", "been", "am", "is", "are",
        "was", "were", "be", "a", "an", "the", "and", "or", "but", "for",
        "of", "in", "on", "to", "with", "from", "also", "very", "really",
        "been", "having", "feeling", "feel", "lot", "much", "some", "few",
        "days", "day", "week", "weeks", "month", "months", "ago", "since",
        "get", "getting", "got", "its", "it", "that", "this", "so", "too",
        "not", "no", "don't", "can't", "just", "like", "sometimes", "often",
        "always", "recently", "today", "yesterday", "last", "past", "about",
    }

    for token in leftover_tokens:
        if token in stop_words or len(token) <= 2:
            continue
        if token in MEDICAL_LEXICON:
            matched.add(MEDICAL_LEXICON[token])
        else:
            unrecognized.append(token)

    return {
        "matched": sorted(matched),
        "unrecognized": unrecognized,
    }
